# Generated by Django 4.2.5 on 2023-09-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="municipio",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pais",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalogo.pais"
            ),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalogo.departamento"
            ),
        ),
    ]
