# Generated by Django 4.2.4 on 2023-09-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_departamento_status_municipio_status_pais_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogo.pais"
            ),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogo.departamento"
            ),
        ),
    ]
